// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOa_a4ZUfh_i-fwE2BP6xH84dr7tCATBw',
    appId: '1:542953151063:web:cbe6b9e737f3012e636112',
    messagingSenderId: '542953151063',
    projectId: 'eassyshopping-7bf2a',
    authDomain: 'eassyshopping-7bf2a.firebaseapp.com',
    storageBucket: 'eassyshopping-7bf2a.firebasestorage.app',
    measurementId: 'G-70WX28S438',
    databaseURL: 'https://eassyshopping-7bf2a-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLXBVEbx0RmQWrSxJH8XS3oTq_DA_KCMQ',
    appId: '1:542953151063:android:b619830a9373c35e636112',
    messagingSenderId: '542953151063',
    projectId: 'eassyshopping-7bf2a',
    storageBucket: 'eassyshopping-7bf2a.firebasestorage.app',
    databaseURL: 'https://eassyshopping-7bf2a-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWHbQ04byGHjma5sjunkuZYBtgEW7l9Q',
    appId: '1:542953151063:ios:c9d1d8aa21959c92636112',
    messagingSenderId: '542953151063',
    projectId: 'eassyshopping-7bf2a',
    storageBucket: 'eassyshopping-7bf2a.firebasestorage.app',
    iosBundleId: 'com.example.shoopingapp',
    databaseURL: 'https://eassyshopping-7bf2a-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbWHbQ04byGHjma5sjunkuZYBtgEW7l9Q',
    appId: '1:542953151063:ios:c9d1d8aa21959c92636112',
    messagingSenderId: '542953151063',
    projectId: 'eassyshopping-7bf2a',
    storageBucket: 'eassyshopping-7bf2a.firebasestorage.app',
    iosBundleId: 'com.example.shoopingapp',
    databaseURL: 'https://eassyshopping-7bf2a-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOa_a4ZUfh_i-fwE2BP6xH84dr7tCATBw',
    appId: '1:542953151063:web:d0ed74da7791b78c636112',
    messagingSenderId: '542953151063',
    projectId: 'eassyshopping-7bf2a',
    authDomain: 'eassyshopping-7bf2a.firebaseapp.com',
    storageBucket: 'eassyshopping-7bf2a.firebasestorage.app',
    measurementId: 'G-L8JWNSQV91',
    databaseURL: 'https://eassyshopping-7bf2a-default-rtdb.firebaseio.com/',
  );
}
